using System;

namespace D_API.Types.Auth
{
    /// <summary>
    /// The credentials received from the user
    /// </summary>
    public sealed class UserRequestCredentials
    {
        public string? UserKey { get; init; }
        public string? Secret { get; init; }
        public string? Identifier { get; init; }
    }

    /// <summary>
    /// The credentials generated by the endpoint once validated and sanitized
    /// </summary>
    public sealed class UserValidCredentials
    {
        /// <summary>
        /// The user key
        /// </summary>
        public Guid Key { get; private init; }

        /// <summary>
        /// The user's UNHASHED secret
        /// </summary>
        public string Secret { get; private init; }

        /// <summary>
        /// The user's identifier
        /// </summary>
        public string Identifier { get; private init; }

        public UserValidCredentials(Guid key, string secret, string identifier)
        {
            Key = key;
            Secret = secret;
            Identifier = identifier;
        }
    }
}
