namespace D_API.Types.Auth;

/// <summary>
/// The credentials received from the client
/// </summary>
public sealed class ClientRequestCredentials
{
    public string? Key { get; init; }
    public string? Secret { get; init; }
    public string? Identifier { get; init; }
}

/// <summary>
/// The credentials generated by the endpoint once validated and sanitized
/// </summary>
public sealed class ClientValidCredentials
{
    /// <summary>
    /// The user key
    /// </summary>
    public Guid Key { get; private init; }

    /// <summary>
    /// The user secret
    /// </summary>
    public string Secret { get; private init; }

    /// <summary>
    /// The client's identifier
    /// </summary>
    public string Identifier { get; private init; }

    public ClientValidCredentials(Guid key, string secret, string identifier)
    {
        Key = key;
        Secret = secret;
        Identifier = identifier;
    }
}